# Generated by Django 2.2 on 2020-05-30 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200528_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_profile_pictures'),
            preserve_default=False,
        ),
    ]
